/**
 * This class is generated by jOOQ
 */
package io.github.ibuildthecloud.dstack.core.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "ip_address", schema = "dstack")
public class IpAddressRecord extends org.jooq.impl.UpdatableRecordImpl<io.github.ibuildthecloud.dstack.core.model.tables.records.IpAddressRecord> implements io.github.ibuildthecloud.dstack.db.jooq.utils.TableRecordJaxb, org.jooq.Record14<java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.Long, java.util.Date, java.util.Date, java.util.Date, java.lang.String, java.lang.String>, io.github.ibuildthecloud.dstack.core.model.IpAddress {

	private static final long serialVersionUID = 1633546607;

	/**
	 * Setter for <code>dstack.ip_address.id</code>.
	 */
	@Override
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dstack.ip_address.id</code>.
	 */
	@javax.persistence.Id
	@javax.persistence.Column(name = "id", unique = true, nullable = false, precision = 19)
	@Override
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>dstack.ip_address.address</code>.
	 */
	@Override
	public void setAddress(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dstack.ip_address.address</code>.
	 */
	@javax.persistence.Column(name = "address", nullable = false, length = 128)
	@Override
	public java.lang.String getAddress() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>dstack.ip_address.account_id</code>.
	 */
	@Override
	public void setAccountId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dstack.ip_address.account_id</code>.
	 */
	@javax.persistence.Column(name = "account_id", nullable = false, precision = 19)
	@Override
	public java.lang.Long getAccountId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>dstack.ip_address.netmask</code>.
	 */
	@Override
	public void setNetmask(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dstack.ip_address.netmask</code>.
	 */
	@javax.persistence.Column(name = "netmask", length = 128)
	@Override
	public java.lang.String getNetmask() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>dstack.ip_address.gateway</code>.
	 */
	@Override
	public void setGateway(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>dstack.ip_address.gateway</code>.
	 */
	@javax.persistence.Column(name = "gateway", length = 128)
	@Override
	public java.lang.String getGateway() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>dstack.ip_address.version</code>.
	 */
	@Override
	public void setVersion(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>dstack.ip_address.version</code>.
	 */
	@javax.persistence.Column(name = "version", nullable = false, length = 255)
	@Override
	public java.lang.String getVersion() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>dstack.ip_address.vnet_id</code>.
	 */
	@Override
	public void setVnetId(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>dstack.ip_address.vnet_id</code>.
	 */
	@javax.persistence.Column(name = "vnet_id", precision = 19)
	@Override
	public java.lang.Long getVnetId() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>dstack.ip_address.ip_assignment_type</code>.
	 */
	@Override
	public void setIpAssignmentType(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>dstack.ip_address.ip_assignment_type</code>.
	 */
	@javax.persistence.Column(name = "ip_assignment_type", length = 255)
	@Override
	public java.lang.String getIpAssignmentType() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>dstack.ip_address.item_pool_id</code>.
	 */
	@Override
	public void setItemPoolId(java.lang.Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>dstack.ip_address.item_pool_id</code>.
	 */
	@javax.persistence.Column(name = "item_pool_id", precision = 19)
	@Override
	public java.lang.Long getItemPoolId() {
		return (java.lang.Long) getValue(8);
	}

	/**
	 * Setter for <code>dstack.ip_address.created</code>.
	 */
	@Override
	public void setCreated(java.util.Date value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>dstack.ip_address.created</code>.
	 */
	@javax.persistence.Column(name = "created")
	@Override
	public java.util.Date getCreated() {
		return (java.util.Date) getValue(9);
	}

	/**
	 * Setter for <code>dstack.ip_address.removed</code>.
	 */
	@Override
	public void setRemoved(java.util.Date value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>dstack.ip_address.removed</code>.
	 */
	@javax.persistence.Column(name = "removed")
	@Override
	public java.util.Date getRemoved() {
		return (java.util.Date) getValue(10);
	}

	/**
	 * Setter for <code>dstack.ip_address.remove_time</code>.
	 */
	@Override
	public void setRemoveTime(java.util.Date value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>dstack.ip_address.remove_time</code>.
	 */
	@javax.persistence.Column(name = "remove_time")
	@Override
	public java.util.Date getRemoveTime() {
		return (java.util.Date) getValue(11);
	}

	/**
	 * Setter for <code>dstack.ip_address.name</code>.
	 */
	@Override
	public void setName(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>dstack.ip_address.name</code>.
	 */
	@javax.persistence.Column(name = "name", length = 255)
	@Override
	public java.lang.String getName() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>dstack.ip_address.description</code>.
	 */
	@Override
	public void setDescription(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>dstack.ip_address.description</code>.
	 */
	@javax.persistence.Column(name = "description", length = 1024)
	@Override
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(13);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record14 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.Long, java.util.Date, java.util.Date, java.util.Date, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row14) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.Long, java.util.Date, java.util.Date, java.util.Date, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row14) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS.ACCOUNT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS.NETMASK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS.GATEWAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS.VNET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS.IP_ASSIGNMENT_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field9() {
		return io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS.ITEM_POOL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.Date> field10() {
		return io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.Date> field11() {
		return io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS.REMOVED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.Date> field12() {
		return io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS.REMOVE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getNetmask();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getGateway();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getVnetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getIpAssignmentType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value9() {
		return getItemPoolId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.Date value10() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.Date value11() {
		return getRemoved();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.Date value12() {
		return getRemoveTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IpAddressRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IpAddressRecord value2(java.lang.String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IpAddressRecord value3(java.lang.Long value) {
		setAccountId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IpAddressRecord value4(java.lang.String value) {
		setNetmask(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IpAddressRecord value5(java.lang.String value) {
		setGateway(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IpAddressRecord value6(java.lang.String value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IpAddressRecord value7(java.lang.Long value) {
		setVnetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IpAddressRecord value8(java.lang.String value) {
		setIpAssignmentType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IpAddressRecord value9(java.lang.Long value) {
		setItemPoolId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IpAddressRecord value10(java.util.Date value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IpAddressRecord value11(java.util.Date value) {
		setRemoved(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IpAddressRecord value12(java.util.Date value) {
		setRemoveTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IpAddressRecord value13(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IpAddressRecord value14(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IpAddressRecord values(java.lang.Long value1, java.lang.String value2, java.lang.Long value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.Long value7, java.lang.String value8, java.lang.Long value9, java.util.Date value10, java.util.Date value11, java.util.Date value12, java.lang.String value13, java.lang.String value14) {
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(io.github.ibuildthecloud.dstack.core.model.IpAddress from) {
		setId(from.getId());
		setAddress(from.getAddress());
		setAccountId(from.getAccountId());
		setNetmask(from.getNetmask());
		setGateway(from.getGateway());
		setVersion(from.getVersion());
		setVnetId(from.getVnetId());
		setIpAssignmentType(from.getIpAssignmentType());
		setItemPoolId(from.getItemPoolId());
		setCreated(from.getCreated());
		setRemoved(from.getRemoved());
		setRemoveTime(from.getRemoveTime());
		setName(from.getName());
		setDescription(from.getDescription());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends io.github.ibuildthecloud.dstack.core.model.IpAddress> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IpAddressRecord
	 */
	public IpAddressRecord() {
		super(io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS);
	}

	/**
	 * Create a detached, initialised IpAddressRecord
	 */
	public IpAddressRecord(java.lang.Long id, java.lang.String address, java.lang.Long accountId, java.lang.String netmask, java.lang.String gateway, java.lang.String version, java.lang.Long vnetId, java.lang.String ipAssignmentType, java.lang.Long itemPoolId, java.util.Date created, java.util.Date removed, java.util.Date removeTime, java.lang.String name, java.lang.String description) {
		super(io.github.ibuildthecloud.dstack.core.model.tables.IpAddressTable.IP_ADDRESS);

		setValue(0, id);
		setValue(1, address);
		setValue(2, accountId);
		setValue(3, netmask);
		setValue(4, gateway);
		setValue(5, version);
		setValue(6, vnetId);
		setValue(7, ipAssignmentType);
		setValue(8, itemPoolId);
		setValue(9, created);
		setValue(10, removed);
		setValue(11, removeTime);
		setValue(12, name);
		setValue(13, description);
	}
}
