/**
 * This class is generated by jOOQ
 */
package io.github.ibuildthecloud.dstack.core.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "nic", schema = "dstack")
public class NicRecord extends org.jooq.impl.UpdatableRecordImpl<io.github.ibuildthecloud.dstack.core.model.tables.records.NicRecord> implements io.github.ibuildthecloud.dstack.db.jooq.utils.TableRecordJaxb, org.jooq.Record11<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp>, io.github.ibuildthecloud.dstack.core.model.Nic {

	private static final long serialVersionUID = -1769466226;

	/**
	 * Setter for <code>dstack.nic.id</code>. 
	 */
	@Override
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dstack.nic.id</code>. 
	 */
	@javax.persistence.Id
	@javax.persistence.Column(name = "id", unique = true, nullable = false, precision = 19)
	@Override
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>dstack.nic.instance_id</code>. 
	 */
	@Override
	public void setInstanceId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dstack.nic.instance_id</code>. 
	 */
	@javax.persistence.Column(name = "instance_id", nullable = false, precision = 19)
	@Override
	public java.lang.Long getInstanceId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>dstack.nic.network_id</code>. 
	 */
	@Override
	public void setNetworkId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dstack.nic.network_id</code>. 
	 */
	@javax.persistence.Column(name = "network_id", nullable = false, precision = 19)
	@Override
	public java.lang.Long getNetworkId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>dstack.nic.account_id</code>. 
	 */
	@Override
	public void setAccountId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dstack.nic.account_id</code>. 
	 */
	@javax.persistence.Column(name = "account_id", nullable = false, precision = 19)
	@Override
	public java.lang.Long getAccountId() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>dstack.nic.state</code>. 
	 */
	@Override
	public void setState(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>dstack.nic.state</code>. 
	 */
	@javax.persistence.Column(name = "state", nullable = false, length = 255)
	@Override
	public java.lang.String getState() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>dstack.nic.mac_address</code>. 
	 */
	@Override
	public void setMacAddress(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>dstack.nic.mac_address</code>. 
	 */
	@javax.persistence.Column(name = "mac_address", length = 17)
	@Override
	public java.lang.String getMacAddress() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>dstack.nic.device_number</code>. 
	 */
	@Override
	public void setDeviceNumber(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>dstack.nic.device_number</code>. 
	 */
	@javax.persistence.Column(name = "device_number", nullable = false, precision = 10)
	@Override
	public java.lang.Integer getDeviceNumber() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>dstack.nic.uuid</code>. 
	 */
	@Override
	public void setUuid(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>dstack.nic.uuid</code>. 
	 */
	@javax.persistence.Column(name = "uuid", nullable = false, length = 255)
	@Override
	public java.lang.String getUuid() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>dstack.nic.created</code>. 
	 */
	@Override
	public void setCreated(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>dstack.nic.created</code>. 
	 */
	@javax.persistence.Column(name = "created")
	@Override
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>dstack.nic.removed</code>. 
	 */
	@Override
	public void setRemoved(java.sql.Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>dstack.nic.removed</code>. 
	 */
	@javax.persistence.Column(name = "removed")
	@Override
	public java.sql.Timestamp getRemoved() {
		return (java.sql.Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>dstack.nic.remove_time</code>. 
	 */
	@Override
	public void setRemoveTime(java.sql.Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>dstack.nic.remove_time</code>. 
	 */
	@javax.persistence.Column(name = "remove_time")
	@Override
	public java.sql.Timestamp getRemoveTime() {
		return (java.sql.Timestamp) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return io.github.ibuildthecloud.dstack.core.model.tables.NicTable.NIC.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return io.github.ibuildthecloud.dstack.core.model.tables.NicTable.NIC.INSTANCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return io.github.ibuildthecloud.dstack.core.model.tables.NicTable.NIC.NETWORK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return io.github.ibuildthecloud.dstack.core.model.tables.NicTable.NIC.ACCOUNT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return io.github.ibuildthecloud.dstack.core.model.tables.NicTable.NIC.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return io.github.ibuildthecloud.dstack.core.model.tables.NicTable.NIC.MAC_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return io.github.ibuildthecloud.dstack.core.model.tables.NicTable.NIC.DEVICE_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return io.github.ibuildthecloud.dstack.core.model.tables.NicTable.NIC.UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return io.github.ibuildthecloud.dstack.core.model.tables.NicTable.NIC.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field10() {
		return io.github.ibuildthecloud.dstack.core.model.tables.NicTable.NIC.REMOVED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field11() {
		return io.github.ibuildthecloud.dstack.core.model.tables.NicTable.NIC.REMOVE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getInstanceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getNetworkId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getMacAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getDeviceNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value10() {
		return getRemoved();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value11() {
		return getRemoveTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NicRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NicRecord value2(java.lang.Long value) {
		setInstanceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NicRecord value3(java.lang.Long value) {
		setNetworkId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NicRecord value4(java.lang.Long value) {
		setAccountId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NicRecord value5(java.lang.String value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NicRecord value6(java.lang.String value) {
		setMacAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NicRecord value7(java.lang.Integer value) {
		setDeviceNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NicRecord value8(java.lang.String value) {
		setUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NicRecord value9(java.sql.Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NicRecord value10(java.sql.Timestamp value) {
		setRemoved(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NicRecord value11(java.sql.Timestamp value) {
		setRemoveTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NicRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Long value3, java.lang.Long value4, java.lang.String value5, java.lang.String value6, java.lang.Integer value7, java.lang.String value8, java.sql.Timestamp value9, java.sql.Timestamp value10, java.sql.Timestamp value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(io.github.ibuildthecloud.dstack.core.model.Nic from) {
		setId(from.getId());
		setInstanceId(from.getInstanceId());
		setNetworkId(from.getNetworkId());
		setAccountId(from.getAccountId());
		setState(from.getState());
		setMacAddress(from.getMacAddress());
		setDeviceNumber(from.getDeviceNumber());
		setUuid(from.getUuid());
		setCreated(from.getCreated());
		setRemoved(from.getRemoved());
		setRemoveTime(from.getRemoveTime());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends io.github.ibuildthecloud.dstack.core.model.Nic> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NicRecord
	 */
	public NicRecord() {
		super(io.github.ibuildthecloud.dstack.core.model.tables.NicTable.NIC);
	}

	/**
	 * Create a detached, initialised NicRecord
	 */
	public NicRecord(java.lang.Long id, java.lang.Long instanceId, java.lang.Long networkId, java.lang.Long accountId, java.lang.String state, java.lang.String macAddress, java.lang.Integer deviceNumber, java.lang.String uuid, java.sql.Timestamp created, java.sql.Timestamp removed, java.sql.Timestamp removeTime) {
		super(io.github.ibuildthecloud.dstack.core.model.tables.NicTable.NIC);

		setValue(0, id);
		setValue(1, instanceId);
		setValue(2, networkId);
		setValue(3, accountId);
		setValue(4, state);
		setValue(5, macAddress);
		setValue(6, deviceNumber);
		setValue(7, uuid);
		setValue(8, created);
		setValue(9, removed);
		setValue(10, removeTime);
	}
}
