/**
 * This class is generated by jOOQ
 */
package io.github.ibuildthecloud.dstack.core.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatabasechangeloglockTable extends org.jooq.impl.TableImpl<io.github.ibuildthecloud.dstack.core.model.tables.records.DatabasechangeloglockRecord> {

	private static final long serialVersionUID = -1265018199;

	/**
	 * The singleton instance of <code>dstack.DATABASECHANGELOGLOCK</code>
	 */
	public static final io.github.ibuildthecloud.dstack.core.model.tables.DatabasechangeloglockTable DATABASECHANGELOGLOCK = new io.github.ibuildthecloud.dstack.core.model.tables.DatabasechangeloglockTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.github.ibuildthecloud.dstack.core.model.tables.records.DatabasechangeloglockRecord> getRecordType() {
		return io.github.ibuildthecloud.dstack.core.model.tables.records.DatabasechangeloglockRecord.class;
	}

	/**
	 * The column <code>dstack.DATABASECHANGELOGLOCK.ID</code>. 
	 */
	public final org.jooq.TableField<io.github.ibuildthecloud.dstack.core.model.tables.records.DatabasechangeloglockRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>dstack.DATABASECHANGELOGLOCK.LOCKED</code>. 
	 */
	public final org.jooq.TableField<io.github.ibuildthecloud.dstack.core.model.tables.records.DatabasechangeloglockRecord, java.lang.Boolean> LOCKED = createField("LOCKED", org.jooq.impl.SQLDataType.BIT.nullable(false), this);

	/**
	 * The column <code>dstack.DATABASECHANGELOGLOCK.LOCKGRANTED</code>. 
	 */
	public final org.jooq.TableField<io.github.ibuildthecloud.dstack.core.model.tables.records.DatabasechangeloglockRecord, java.sql.Timestamp> LOCKGRANTED = createField("LOCKGRANTED", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>dstack.DATABASECHANGELOGLOCK.LOCKEDBY</code>. 
	 */
	public final org.jooq.TableField<io.github.ibuildthecloud.dstack.core.model.tables.records.DatabasechangeloglockRecord, java.lang.String> LOCKEDBY = createField("LOCKEDBY", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>dstack.DATABASECHANGELOGLOCK</code> table reference
	 */
	public DatabasechangeloglockTable() {
		super("DATABASECHANGELOGLOCK", io.github.ibuildthecloud.dstack.core.model.DstackTable.DSTACK);
	}

	/**
	 * Create an aliased <code>dstack.DATABASECHANGELOGLOCK</code> table reference
	 */
	public DatabasechangeloglockTable(java.lang.String alias) {
		super(alias, io.github.ibuildthecloud.dstack.core.model.DstackTable.DSTACK, io.github.ibuildthecloud.dstack.core.model.tables.DatabasechangeloglockTable.DATABASECHANGELOGLOCK);
	}

	private DatabasechangeloglockTable(java.lang.String alias, org.jooq.Table<io.github.ibuildthecloud.dstack.core.model.tables.records.DatabasechangeloglockRecord> aliased) {
		super(alias, io.github.ibuildthecloud.dstack.core.model.DstackTable.DSTACK, aliased);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<io.github.ibuildthecloud.dstack.core.model.tables.records.DatabasechangeloglockRecord> getPrimaryKey() {
		return io.github.ibuildthecloud.dstack.core.model.Keys.KEY_DATABASECHANGELOGLOCK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.github.ibuildthecloud.dstack.core.model.tables.records.DatabasechangeloglockRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.github.ibuildthecloud.dstack.core.model.tables.records.DatabasechangeloglockRecord>>asList(io.github.ibuildthecloud.dstack.core.model.Keys.KEY_DATABASECHANGELOGLOCK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.github.ibuildthecloud.dstack.core.model.tables.DatabasechangeloglockTable as(java.lang.String alias) {
		return new io.github.ibuildthecloud.dstack.core.model.tables.DatabasechangeloglockTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.github.ibuildthecloud.dstack.core.model.tables.DatabasechangeloglockTable rename(java.lang.String name) {
		return new io.github.ibuildthecloud.dstack.core.model.tables.DatabasechangeloglockTable(name, null);
	}
}
