#!/bin/sh

export CATTLE_REGISTRATION_ACCESS_KEY="${CATTLE_REGISTRATION_ACCESS_KEY}"
export CATTLE_REGISTRATION_SECRET_KEY="${CATTLE_REGISTRATION_SECRET_KEY}"
export CATTLE_URL="${CATTLE_URL}"
export DETECTED_CATTLE_AGENT_IP="${CATTLE_AGENT_IP}"
