---
matrix:
  API_VERSION:
  - v1
  - v2
  ENVIRONMENTS:
  - ( [mysql]=full [h2]=lite )
  - ( [pgsql]=full )

pipeline:
  build:
    privileged: true
    image: rancher/dapper:1.10.3
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - dapper ci
