/*
 * This file is generated by jOOQ.
*/
package io.cattle.platform.core.model.tables.records;


import io.cattle.platform.core.model.ProcessInstance;
import io.cattle.platform.core.model.tables.ProcessInstanceTable;
import io.cattle.platform.db.jooq.utils.TableRecordJaxb;

import java.util.Date;
import java.util.Map;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "process_instance", schema = "cattle")
public class ProcessInstanceRecord extends UpdatableRecordImpl<ProcessInstanceRecord> implements TableRecordJaxb, Record16<Long, Date, Date, Map<String,Object>, Integer, String, String, String, String, String, String, String, String, Long, Date, Long>, ProcessInstance {

    private static final long serialVersionUID = -262319900;

    /**
     * Setter for <code>cattle.process_instance.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cattle.process_instance.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 19)
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cattle.process_instance.start_time</code>.
     */
    @Override
    public void setStartTime(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>cattle.process_instance.start_time</code>.
     */
    @Column(name = "start_time")
    @Override
    public Date getStartTime() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>cattle.process_instance.end_time</code>.
     */
    @Override
    public void setEndTime(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>cattle.process_instance.end_time</code>.
     */
    @Column(name = "end_time")
    @Override
    public Date getEndTime() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>cattle.process_instance.data</code>.
     */
    @Override
    public void setData(Map<String,Object> value) {
        set(3, value);
    }

    /**
     * Getter for <code>cattle.process_instance.data</code>.
     */
    @Column(name = "data", length = 16777215)
    @Override
    public Map<String,Object> getData() {
        return (Map<String,Object>) get(3);
    }

    /**
     * Setter for <code>cattle.process_instance.priority</code>.
     */
    @Override
    public void setPriority(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>cattle.process_instance.priority</code>.
     */
    @Column(name = "priority", precision = 10)
    @Override
    public Integer getPriority() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>cattle.process_instance.process_name</code>.
     */
    @Override
    public void setProcessName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cattle.process_instance.process_name</code>.
     */
    @Column(name = "process_name", length = 128)
    @Override
    public String getProcessName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cattle.process_instance.resource_type</code>.
     */
    @Override
    public void setResourceType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>cattle.process_instance.resource_type</code>.
     */
    @Column(name = "resource_type", length = 128)
    @Override
    public String getResourceType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>cattle.process_instance.resource_id</code>.
     */
    @Override
    public void setResourceId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>cattle.process_instance.resource_id</code>.
     */
    @Column(name = "resource_id", length = 128)
    @Override
    public String getResourceId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>cattle.process_instance.result</code>.
     */
    @Override
    public void setResult(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>cattle.process_instance.result</code>.
     */
    @Column(name = "result", length = 128)
    @Override
    public String getResult() {
        return (String) get(8);
    }

    /**
     * Setter for <code>cattle.process_instance.exit_reason</code>.
     */
    @Override
    public void setExitReason(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>cattle.process_instance.exit_reason</code>.
     */
    @Column(name = "exit_reason", length = 128)
    @Override
    public String getExitReason() {
        return (String) get(9);
    }

    /**
     * Setter for <code>cattle.process_instance.phase</code>.
     */
    @Override
    public void setPhase(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>cattle.process_instance.phase</code>.
     */
    @Column(name = "phase", length = 128)
    @Override
    public String getPhase() {
        return (String) get(10);
    }

    /**
     * Setter for <code>cattle.process_instance.start_process_server_id</code>.
     */
    @Override
    public void setStartProcessServerId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>cattle.process_instance.start_process_server_id</code>.
     */
    @Column(name = "start_process_server_id", length = 128)
    @Override
    public String getStartProcessServerId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>cattle.process_instance.running_process_server_id</code>.
     */
    @Override
    public void setRunningProcessServerId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>cattle.process_instance.running_process_server_id</code>.
     */
    @Column(name = "running_process_server_id", length = 128)
    @Override
    public String getRunningProcessServerId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>cattle.process_instance.execution_count</code>.
     */
    @Override
    public void setExecutionCount(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>cattle.process_instance.execution_count</code>.
     */
    @Column(name = "execution_count", nullable = false, precision = 19)
    @Override
    public Long getExecutionCount() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>cattle.process_instance.run_after</code>.
     */
    @Override
    public void setRunAfter(Date value) {
        set(14, value);
    }

    /**
     * Getter for <code>cattle.process_instance.run_after</code>.
     */
    @Column(name = "run_after")
    @Override
    public Date getRunAfter() {
        return (Date) get(14);
    }

    /**
     * Setter for <code>cattle.process_instance.account_id</code>.
     */
    @Override
    public void setAccountId(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>cattle.process_instance.account_id</code>.
     */
    @Column(name = "account_id", precision = 19)
    @Override
    public Long getAccountId() {
        return (Long) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, Date, Date, Map<String,Object>, Integer, String, String, String, String, String, String, String, String, Long, Date, Long> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, Date, Date, Map<String,Object>, Integer, String, String, String, String, String, String, String, String, Long, Date, Long> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProcessInstanceTable.PROCESS_INSTANCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return ProcessInstanceTable.PROCESS_INSTANCE.START_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return ProcessInstanceTable.PROCESS_INSTANCE.END_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Map<String,Object>> field4() {
        return ProcessInstanceTable.PROCESS_INSTANCE.DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ProcessInstanceTable.PROCESS_INSTANCE.PRIORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ProcessInstanceTable.PROCESS_INSTANCE.PROCESS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ProcessInstanceTable.PROCESS_INSTANCE.RESOURCE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return ProcessInstanceTable.PROCESS_INSTANCE.RESOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ProcessInstanceTable.PROCESS_INSTANCE.RESULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return ProcessInstanceTable.PROCESS_INSTANCE.EXIT_REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return ProcessInstanceTable.PROCESS_INSTANCE.PHASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return ProcessInstanceTable.PROCESS_INSTANCE.START_PROCESS_SERVER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return ProcessInstanceTable.PROCESS_INSTANCE.RUNNING_PROCESS_SERVER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field14() {
        return ProcessInstanceTable.PROCESS_INSTANCE.EXECUTION_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field15() {
        return ProcessInstanceTable.PROCESS_INSTANCE.RUN_AFTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field16() {
        return ProcessInstanceTable.PROCESS_INSTANCE.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Map<String,Object> value4() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getProcessName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getResourceType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getResourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getExitReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getPhase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getStartProcessServerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getRunningProcessServerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value14() {
        return getExecutionCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value15() {
        return getRunAfter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value16() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value2(Date value) {
        setStartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value3(Date value) {
        setEndTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value4(Map<String,Object> value) {
        setData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value5(Integer value) {
        setPriority(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value6(String value) {
        setProcessName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value7(String value) {
        setResourceType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value8(String value) {
        setResourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value9(String value) {
        setResult(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value10(String value) {
        setExitReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value11(String value) {
        setPhase(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value12(String value) {
        setStartProcessServerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value13(String value) {
        setRunningProcessServerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value14(Long value) {
        setExecutionCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value15(Date value) {
        setRunAfter(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord value16(Long value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessInstanceRecord values(Long value1, Date value2, Date value3, Map<String,Object> value4, Integer value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, Long value14, Date value15, Long value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ProcessInstance from) {
        setId(from.getId());
        setStartTime(from.getStartTime());
        setEndTime(from.getEndTime());
        setData(from.getData());
        setPriority(from.getPriority());
        setProcessName(from.getProcessName());
        setResourceType(from.getResourceType());
        setResourceId(from.getResourceId());
        setResult(from.getResult());
        setExitReason(from.getExitReason());
        setPhase(from.getPhase());
        setStartProcessServerId(from.getStartProcessServerId());
        setRunningProcessServerId(from.getRunningProcessServerId());
        setExecutionCount(from.getExecutionCount());
        setRunAfter(from.getRunAfter());
        setAccountId(from.getAccountId());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ProcessInstance> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessInstanceRecord
     */
    public ProcessInstanceRecord() {
        super(ProcessInstanceTable.PROCESS_INSTANCE);
    }

    /**
     * Create a detached, initialised ProcessInstanceRecord
     */
    public ProcessInstanceRecord(Long id, Date startTime, Date endTime, Map<String,Object> data, Integer priority, String processName, String resourceType, String resourceId, String result, String exitReason, String phase, String startProcessServerId, String runningProcessServerId, Long executionCount, Date runAfter, Long accountId) {
        super(ProcessInstanceTable.PROCESS_INSTANCE);

        set(0, id);
        set(1, startTime);
        set(2, endTime);
        set(3, data);
        set(4, priority);
        set(5, processName);
        set(6, resourceType);
        set(7, resourceId);
        set(8, result);
        set(9, exitReason);
        set(10, phase);
        set(11, startProcessServerId);
        set(12, runningProcessServerId);
        set(13, executionCount);
        set(14, runAfter);
        set(15, accountId);
    }
}
