/**
 * This class is generated by jOOQ
 */
package io.cattle.platform.core.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "dynamic_schema_role", schema = "cattle")
public class DynamicSchemaRoleRecord extends org.jooq.impl.UpdatableRecordImpl<io.cattle.platform.core.model.tables.records.DynamicSchemaRoleRecord> implements io.cattle.platform.db.jooq.utils.TableRecordJaxb, org.jooq.Record3<java.lang.Long, java.lang.Long, java.lang.String>, io.cattle.platform.core.model.DynamicSchemaRole {

	private static final long serialVersionUID = -1450949241;

	/**
	 * Setter for <code>cattle.dynamic_schema_role.id</code>.
	 */
	@Override
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cattle.dynamic_schema_role.id</code>.
	 */
	@javax.persistence.Id
	@javax.persistence.Column(name = "id", unique = true, nullable = false, precision = 19)
	@Override
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cattle.dynamic_schema_role.dynamic_schema_id</code>.
	 */
	@Override
	public void setDynamicSchemaId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cattle.dynamic_schema_role.dynamic_schema_id</code>.
	 */
	@javax.persistence.Column(name = "dynamic_schema_id", precision = 19)
	@Override
	public java.lang.Long getDynamicSchemaId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>cattle.dynamic_schema_role.role</code>.
	 */
	@Override
	public void setRole(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cattle.dynamic_schema_role.role</code>.
	 */
	@javax.persistence.Column(name = "role", nullable = false, length = 255)
	@Override
	public java.lang.String getRole() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return io.cattle.platform.core.model.tables.DynamicSchemaRoleTable.DYNAMIC_SCHEMA_ROLE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return io.cattle.platform.core.model.tables.DynamicSchemaRoleTable.DYNAMIC_SCHEMA_ROLE.DYNAMIC_SCHEMA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return io.cattle.platform.core.model.tables.DynamicSchemaRoleTable.DYNAMIC_SCHEMA_ROLE.ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getDynamicSchemaId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getRole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DynamicSchemaRoleRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DynamicSchemaRoleRecord value2(java.lang.Long value) {
		setDynamicSchemaId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DynamicSchemaRoleRecord value3(java.lang.String value) {
		setRole(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DynamicSchemaRoleRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(io.cattle.platform.core.model.DynamicSchemaRole from) {
		setId(from.getId());
		setDynamicSchemaId(from.getDynamicSchemaId());
		setRole(from.getRole());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends io.cattle.platform.core.model.DynamicSchemaRole> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DynamicSchemaRoleRecord
	 */
	public DynamicSchemaRoleRecord() {
		super(io.cattle.platform.core.model.tables.DynamicSchemaRoleTable.DYNAMIC_SCHEMA_ROLE);
	}

	/**
	 * Create a detached, initialised DynamicSchemaRoleRecord
	 */
	public DynamicSchemaRoleRecord(java.lang.Long id, java.lang.Long dynamicSchemaId, java.lang.String role) {
		super(io.cattle.platform.core.model.tables.DynamicSchemaRoleTable.DYNAMIC_SCHEMA_ROLE);

		setValue(0, id);
		setValue(1, dynamicSchemaId);
		setValue(2, role);
	}
}
