/**
 * This class is generated by jOOQ
 */
package io.cattle.platform.core.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BackoffTable extends org.jooq.impl.TableImpl<io.cattle.platform.core.model.tables.records.BackoffRecord> {

	private static final long serialVersionUID = -1104782752;

	/**
	 * The singleton instance of <code>cattle.backoff</code>
	 */
	public static final io.cattle.platform.core.model.tables.BackoffTable BACKOFF = new io.cattle.platform.core.model.tables.BackoffTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.cattle.platform.core.model.tables.records.BackoffRecord> getRecordType() {
		return io.cattle.platform.core.model.tables.records.BackoffRecord.class;
	}

	/**
	 * The column <code>cattle.backoff.id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.BackoffRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>cattle.backoff.resource_type</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.BackoffRecord, java.lang.String> RESOURCE_TYPE = createField("resource_type", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>cattle.backoff.resource_id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.BackoffRecord, java.lang.Long> RESOURCE_ID = createField("resource_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>cattle.backoff.count</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.BackoffRecord, java.lang.Long> COUNT = createField("count", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>cattle.backoff.period</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.BackoffRecord, java.lang.Long> PERIOD = createField("period", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>cattle.backoff</code> table reference
	 */
	public BackoffTable() {
		this("backoff", null);
	}

	/**
	 * Create an aliased <code>cattle.backoff</code> table reference
	 */
	public BackoffTable(java.lang.String alias) {
		this(alias, io.cattle.platform.core.model.tables.BackoffTable.BACKOFF);
	}

	private BackoffTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.BackoffRecord> aliased) {
		this(alias, aliased, null);
	}

	private BackoffTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.BackoffRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, io.cattle.platform.core.model.CattleTable.CATTLE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<io.cattle.platform.core.model.tables.records.BackoffRecord, java.lang.Long> getIdentity() {
		return io.cattle.platform.core.model.Keys.IDENTITY_BACKOFF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.BackoffRecord> getPrimaryKey() {
		return io.cattle.platform.core.model.Keys.KEY_BACKOFF_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.BackoffRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.BackoffRecord>>asList(io.cattle.platform.core.model.Keys.KEY_BACKOFF_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.cattle.platform.core.model.tables.BackoffTable as(java.lang.String alias) {
		return new io.cattle.platform.core.model.tables.BackoffTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.cattle.platform.core.model.tables.BackoffTable rename(java.lang.String name) {
		return new io.cattle.platform.core.model.tables.BackoffTable(name, null);
	}
}
