/**
 * This class is generated by jOOQ
 */
package io.cattle.platform.core.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CredentialInstanceMapTable extends org.jooq.impl.TableImpl<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord> {

	private static final long serialVersionUID = -1975210452;

	/**
	 * The singleton instance of <code>cattle.credential_instance_map</code>
	 */
	public static final io.cattle.platform.core.model.tables.CredentialInstanceMapTable CREDENTIAL_INSTANCE_MAP = new io.cattle.platform.core.model.tables.CredentialInstanceMapTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord> getRecordType() {
		return io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord.class;
	}

	/**
	 * The column <code>cattle.credential_instance_map.id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>cattle.credential_instance_map.name</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>cattle.credential_instance_map.kind</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord, java.lang.String> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>cattle.credential_instance_map.uuid</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord, java.lang.String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>cattle.credential_instance_map.description</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>cattle.credential_instance_map.state</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>cattle.credential_instance_map.created</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord, java.util.Date> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.credential_instance_map.removed</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord, java.util.Date> REMOVED = createField("removed", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.credential_instance_map.remove_time</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord, java.util.Date> REMOVE_TIME = createField("remove_time", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.credential_instance_map.data</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord, java.util.Map<String,Object>> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB.length(65535).asConvertedDataType(new io.cattle.platform.db.jooq.converter.DataConverter()), this, "");

	/**
	 * The column <code>cattle.credential_instance_map.credential_id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord, java.lang.Long> CREDENTIAL_ID = createField("credential_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>cattle.credential_instance_map.instance_id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord, java.lang.Long> INSTANCE_ID = createField("instance_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>cattle.credential_instance_map</code> table reference
	 */
	public CredentialInstanceMapTable() {
		this("credential_instance_map", null);
	}

	/**
	 * Create an aliased <code>cattle.credential_instance_map</code> table reference
	 */
	public CredentialInstanceMapTable(java.lang.String alias) {
		this(alias, io.cattle.platform.core.model.tables.CredentialInstanceMapTable.CREDENTIAL_INSTANCE_MAP);
	}

	private CredentialInstanceMapTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord> aliased) {
		this(alias, aliased, null);
	}

	private CredentialInstanceMapTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, io.cattle.platform.core.model.CattleTable.CATTLE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord, java.lang.Long> getIdentity() {
		return io.cattle.platform.core.model.Keys.IDENTITY_CREDENTIAL_INSTANCE_MAP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord> getPrimaryKey() {
		return io.cattle.platform.core.model.Keys.KEY_CREDENTIAL_INSTANCE_MAP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord>>asList(io.cattle.platform.core.model.Keys.KEY_CREDENTIAL_INSTANCE_MAP_PRIMARY, io.cattle.platform.core.model.Keys.KEY_CREDENTIAL_INSTANCE_MAP_IDX_CREDENTIAL_INSTANCE_MAP_UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<io.cattle.platform.core.model.tables.records.CredentialInstanceMapRecord, ?>>asList(io.cattle.platform.core.model.Keys.FK_CREDENTIAL_INSTANCE_MAP__CREDENTIAL_ID, io.cattle.platform.core.model.Keys.FK_CREDENTIAL_INSTANCE_MAP__INSTANCE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.cattle.platform.core.model.tables.CredentialInstanceMapTable as(java.lang.String alias) {
		return new io.cattle.platform.core.model.tables.CredentialInstanceMapTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.cattle.platform.core.model.tables.CredentialInstanceMapTable rename(java.lang.String name) {
		return new io.cattle.platform.core.model.tables.CredentialInstanceMapTable(name, null);
	}
}
