/**
 * This class is generated by jOOQ
 */
package io.cattle.platform.core.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatabasechangeloglockTable extends org.jooq.impl.TableImpl<io.cattle.platform.core.model.tables.records.DatabasechangeloglockRecord> {

	private static final long serialVersionUID = 1759341827;

	/**
	 * The singleton instance of <code>cattle.DATABASECHANGELOGLOCK</code>
	 */
	public static final io.cattle.platform.core.model.tables.DatabasechangeloglockTable DATABASECHANGELOGLOCK = new io.cattle.platform.core.model.tables.DatabasechangeloglockTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.cattle.platform.core.model.tables.records.DatabasechangeloglockRecord> getRecordType() {
		return io.cattle.platform.core.model.tables.records.DatabasechangeloglockRecord.class;
	}

	/**
	 * The column <code>cattle.DATABASECHANGELOGLOCK.ID</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.DatabasechangeloglockRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cattle.DATABASECHANGELOGLOCK.LOCKED</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.DatabasechangeloglockRecord, java.lang.Boolean> LOCKED = createField("LOCKED", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

	/**
	 * The column <code>cattle.DATABASECHANGELOGLOCK.LOCKGRANTED</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.DatabasechangeloglockRecord, java.util.Date> LOCKGRANTED = createField("LOCKGRANTED", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.DATABASECHANGELOGLOCK.LOCKEDBY</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.DatabasechangeloglockRecord, java.lang.String> LOCKEDBY = createField("LOCKEDBY", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>cattle.DATABASECHANGELOGLOCK</code> table reference
	 */
	public DatabasechangeloglockTable() {
		this("DATABASECHANGELOGLOCK", null);
	}

	/**
	 * Create an aliased <code>cattle.DATABASECHANGELOGLOCK</code> table reference
	 */
	public DatabasechangeloglockTable(java.lang.String alias) {
		this(alias, io.cattle.platform.core.model.tables.DatabasechangeloglockTable.DATABASECHANGELOGLOCK);
	}

	private DatabasechangeloglockTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.DatabasechangeloglockRecord> aliased) {
		this(alias, aliased, null);
	}

	private DatabasechangeloglockTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.DatabasechangeloglockRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, io.cattle.platform.core.model.CattleTable.CATTLE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.DatabasechangeloglockRecord> getPrimaryKey() {
		return io.cattle.platform.core.model.Keys.KEY_DATABASECHANGELOGLOCK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.DatabasechangeloglockRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.DatabasechangeloglockRecord>>asList(io.cattle.platform.core.model.Keys.KEY_DATABASECHANGELOGLOCK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.cattle.platform.core.model.tables.DatabasechangeloglockTable as(java.lang.String alias) {
		return new io.cattle.platform.core.model.tables.DatabasechangeloglockTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.cattle.platform.core.model.tables.DatabasechangeloglockTable rename(java.lang.String name) {
		return new io.cattle.platform.core.model.tables.DatabasechangeloglockTable(name, null);
	}
}
