/**
 * This class is generated by jOOQ
 */
package io.cattle.platform.core.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExternalHandlerProcessTable extends org.jooq.impl.TableImpl<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord> {

	private static final long serialVersionUID = -1296185509;

	/**
	 * The singleton instance of <code>cattle.external_handler_process</code>
	 */
	public static final io.cattle.platform.core.model.tables.ExternalHandlerProcessTable EXTERNAL_HANDLER_PROCESS = new io.cattle.platform.core.model.tables.ExternalHandlerProcessTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord> getRecordType() {
		return io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord.class;
	}

	/**
	 * The column <code>cattle.external_handler_process.id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>cattle.external_handler_process.name</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>cattle.external_handler_process.kind</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord, java.lang.String> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>cattle.external_handler_process.uuid</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord, java.lang.String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>cattle.external_handler_process.description</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>cattle.external_handler_process.state</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>cattle.external_handler_process.created</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord, java.util.Date> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.external_handler_process.removed</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord, java.util.Date> REMOVED = createField("removed", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.external_handler_process.remove_time</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord, java.util.Date> REMOVE_TIME = createField("remove_time", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.external_handler_process.data</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord, java.util.Map<String,Object>> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB.length(16777215).asConvertedDataType(new io.cattle.platform.db.jooq.converter.DataConverter()), this, "");

	/**
	 * Create a <code>cattle.external_handler_process</code> table reference
	 */
	public ExternalHandlerProcessTable() {
		this("external_handler_process", null);
	}

	/**
	 * Create an aliased <code>cattle.external_handler_process</code> table reference
	 */
	public ExternalHandlerProcessTable(java.lang.String alias) {
		this(alias, io.cattle.platform.core.model.tables.ExternalHandlerProcessTable.EXTERNAL_HANDLER_PROCESS);
	}

	private ExternalHandlerProcessTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord> aliased) {
		this(alias, aliased, null);
	}

	private ExternalHandlerProcessTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, io.cattle.platform.core.model.CattleTable.CATTLE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord, java.lang.Long> getIdentity() {
		return io.cattle.platform.core.model.Keys.IDENTITY_EXTERNAL_HANDLER_PROCESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord> getPrimaryKey() {
		return io.cattle.platform.core.model.Keys.KEY_EXTERNAL_HANDLER_PROCESS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord>>asList(io.cattle.platform.core.model.Keys.KEY_EXTERNAL_HANDLER_PROCESS_PRIMARY, io.cattle.platform.core.model.Keys.KEY_EXTERNAL_HANDLER_PROCESS_IDX_EXTERNAL_HANDLER_PROCESS_UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.cattle.platform.core.model.tables.ExternalHandlerProcessTable as(java.lang.String alias) {
		return new io.cattle.platform.core.model.tables.ExternalHandlerProcessTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.cattle.platform.core.model.tables.ExternalHandlerProcessTable rename(java.lang.String name) {
		return new io.cattle.platform.core.model.tables.ExternalHandlerProcessTable(name, null);
	}
}
