/*
 * This file is generated by jOOQ.
*/
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.records.ExternalHandlerProcessRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExternalHandlerProcessTable extends TableImpl<ExternalHandlerProcessRecord> {

    private static final long serialVersionUID = -1585836257;

    /**
     * The reference instance of <code>cattle.external_handler_process</code>
     */
    public static final ExternalHandlerProcessTable EXTERNAL_HANDLER_PROCESS = new ExternalHandlerProcessTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExternalHandlerProcessRecord> getRecordType() {
        return ExternalHandlerProcessRecord.class;
    }

    /**
     * The column <code>cattle.external_handler_process.id</code>.
     */
    public final TableField<ExternalHandlerProcessRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cattle.external_handler_process.name</code>.
     */
    public final TableField<ExternalHandlerProcessRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>cattle.external_handler_process.kind</code>.
     */
    public final TableField<ExternalHandlerProcessRecord, String> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>cattle.external_handler_process.uuid</code>.
     */
    public final TableField<ExternalHandlerProcessRecord, String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

    /**
     * The column <code>cattle.external_handler_process.description</code>.
     */
    public final TableField<ExternalHandlerProcessRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

    /**
     * The column <code>cattle.external_handler_process.state</code>.
     */
    public final TableField<ExternalHandlerProcessRecord, String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

    /**
     * The column <code>cattle.external_handler_process.created</code>.
     */
    public final TableField<ExternalHandlerProcessRecord, Date> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new DateConverter());

    /**
     * The column <code>cattle.external_handler_process.removed</code>.
     */
    public final TableField<ExternalHandlerProcessRecord, Date> REMOVED = createField("removed", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new DateConverter());

    /**
     * The column <code>cattle.external_handler_process.remove_time</code>.
     */
    public final TableField<ExternalHandlerProcessRecord, Date> REMOVE_TIME = createField("remove_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new DateConverter());

    /**
     * The column <code>cattle.external_handler_process.data</code>.
     */
    public final TableField<ExternalHandlerProcessRecord, Map<String,Object>> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB, this, "", new DataConverter());

    /**
     * Create a <code>cattle.external_handler_process</code> table reference
     */
    public ExternalHandlerProcessTable() {
        this("external_handler_process", null);
    }

    /**
     * Create an aliased <code>cattle.external_handler_process</code> table reference
     */
    public ExternalHandlerProcessTable(String alias) {
        this(alias, EXTERNAL_HANDLER_PROCESS);
    }

    private ExternalHandlerProcessTable(String alias, Table<ExternalHandlerProcessRecord> aliased) {
        this(alias, aliased, null);
    }

    private ExternalHandlerProcessTable(String alias, Table<ExternalHandlerProcessRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CattleTable.CATTLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ExternalHandlerProcessRecord, Long> getIdentity() {
        return Keys.IDENTITY_EXTERNAL_HANDLER_PROCESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ExternalHandlerProcessRecord> getPrimaryKey() {
        return Keys.KEY_EXTERNAL_HANDLER_PROCESS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ExternalHandlerProcessRecord>> getKeys() {
        return Arrays.<UniqueKey<ExternalHandlerProcessRecord>>asList(Keys.KEY_EXTERNAL_HANDLER_PROCESS_PRIMARY, Keys.KEY_EXTERNAL_HANDLER_PROCESS_IDX_EXTERNAL_HANDLER_PROCESS_UUID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExternalHandlerProcessTable as(String alias) {
        return new ExternalHandlerProcessTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ExternalHandlerProcessTable rename(String name) {
        return new ExternalHandlerProcessTable(name, null);
    }
}
