/**
 * This class is generated by jOOQ
 */
package io.cattle.platform.core.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoadBalancerHostMapTable extends org.jooq.impl.TableImpl<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord> {

	private static final long serialVersionUID = -869927087;

	/**
	 * The singleton instance of <code>cattle.load_balancer_host_map</code>
	 */
	public static final io.cattle.platform.core.model.tables.LoadBalancerHostMapTable LOAD_BALANCER_HOST_MAP = new io.cattle.platform.core.model.tables.LoadBalancerHostMapTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord> getRecordType() {
		return io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord.class;
	}

	/**
	 * The column <code>cattle.load_balancer_host_map.id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>cattle.load_balancer_host_map.name</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>cattle.load_balancer_host_map.kind</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, java.lang.String> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>cattle.load_balancer_host_map.uuid</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, java.lang.String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>cattle.load_balancer_host_map.description</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>cattle.load_balancer_host_map.state</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>cattle.load_balancer_host_map.created</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, java.util.Date> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.load_balancer_host_map.removed</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, java.util.Date> REMOVED = createField("removed", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.load_balancer_host_map.remove_time</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, java.util.Date> REMOVE_TIME = createField("remove_time", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.load_balancer_host_map.data</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, java.util.Map<String,Object>> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB.length(65535).asConvertedDataType(new io.cattle.platform.db.jooq.converter.DataConverter()), this, "");

	/**
	 * The column <code>cattle.load_balancer_host_map.host_id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, java.lang.Long> HOST_ID = createField("host_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>cattle.load_balancer_host_map.load_balancer_id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, java.lang.Long> LOAD_BALANCER_ID = createField("load_balancer_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>cattle.load_balancer_host_map.account_id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, java.lang.Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>cattle.load_balancer_host_map</code> table reference
	 */
	public LoadBalancerHostMapTable() {
		this("load_balancer_host_map", null);
	}

	/**
	 * Create an aliased <code>cattle.load_balancer_host_map</code> table reference
	 */
	public LoadBalancerHostMapTable(java.lang.String alias) {
		this(alias, io.cattle.platform.core.model.tables.LoadBalancerHostMapTable.LOAD_BALANCER_HOST_MAP);
	}

	private LoadBalancerHostMapTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord> aliased) {
		this(alias, aliased, null);
	}

	private LoadBalancerHostMapTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, io.cattle.platform.core.model.CattleTable.CATTLE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, java.lang.Long> getIdentity() {
		return io.cattle.platform.core.model.Keys.IDENTITY_LOAD_BALANCER_HOST_MAP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord> getPrimaryKey() {
		return io.cattle.platform.core.model.Keys.KEY_LOAD_BALANCER_HOST_MAP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord>>asList(io.cattle.platform.core.model.Keys.KEY_LOAD_BALANCER_HOST_MAP_PRIMARY, io.cattle.platform.core.model.Keys.KEY_LOAD_BALANCER_HOST_MAP_IDX_LOAD_BALANCER_HOST_MAP_UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<io.cattle.platform.core.model.tables.records.LoadBalancerHostMapRecord, ?>>asList(io.cattle.platform.core.model.Keys.FK_LOAD_BALANCER_HOST_MAP__HOST_ID, io.cattle.platform.core.model.Keys.FK_LOAD_BALANCER_HOST_MAP__LOAD_BALANCER_ID, io.cattle.platform.core.model.Keys.FK_LOAD_BALANCER_HOST_MAP__ACCOUNT_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.cattle.platform.core.model.tables.LoadBalancerHostMapTable as(java.lang.String alias) {
		return new io.cattle.platform.core.model.tables.LoadBalancerHostMapTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.cattle.platform.core.model.tables.LoadBalancerHostMapTable rename(java.lang.String name) {
		return new io.cattle.platform.core.model.tables.LoadBalancerHostMapTable(name, null);
	}
}
