/**
 * This class is generated by jOOQ
 */
package io.cattle.platform.core.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecretTable extends org.jooq.impl.TableImpl<io.cattle.platform.core.model.tables.records.SecretRecord> {

	private static final long serialVersionUID = 395362675;

	/**
	 * The singleton instance of <code>cattle.secret</code>
	 */
	public static final io.cattle.platform.core.model.tables.SecretTable SECRET = new io.cattle.platform.core.model.tables.SecretTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.cattle.platform.core.model.tables.records.SecretRecord> getRecordType() {
		return io.cattle.platform.core.model.tables.records.SecretRecord.class;
	}

	/**
	 * The column <code>cattle.secret.id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.SecretRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>cattle.secret.name</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.SecretRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>cattle.secret.account_id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.SecretRecord, java.lang.Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>cattle.secret.kind</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.SecretRecord, java.lang.String> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>cattle.secret.uuid</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.SecretRecord, java.lang.String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>cattle.secret.description</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.SecretRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>cattle.secret.state</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.SecretRecord, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>cattle.secret.created</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.SecretRecord, java.util.Date> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.secret.removed</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.SecretRecord, java.util.Date> REMOVED = createField("removed", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.secret.remove_time</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.SecretRecord, java.util.Date> REMOVE_TIME = createField("remove_time", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.secret.data</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.SecretRecord, java.util.Map<String,Object>> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB.length(16777215).asConvertedDataType(new io.cattle.platform.db.jooq.converter.DataConverter()), this, "");

	/**
	 * The column <code>cattle.secret.value</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.SecretRecord, java.lang.String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB.length(16777215), this, "");

	/**
	 * The column <code>cattle.secret.environment_id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.SecretRecord, java.lang.Long> STACK_ID = createField("environment_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>cattle.secret</code> table reference
	 */
	public SecretTable() {
		this("secret", null);
	}

	/**
	 * Create an aliased <code>cattle.secret</code> table reference
	 */
	public SecretTable(java.lang.String alias) {
		this(alias, io.cattle.platform.core.model.tables.SecretTable.SECRET);
	}

	private SecretTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.SecretRecord> aliased) {
		this(alias, aliased, null);
	}

	private SecretTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.SecretRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, io.cattle.platform.core.model.CattleTable.CATTLE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<io.cattle.platform.core.model.tables.records.SecretRecord, java.lang.Long> getIdentity() {
		return io.cattle.platform.core.model.Keys.IDENTITY_SECRET;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.SecretRecord> getPrimaryKey() {
		return io.cattle.platform.core.model.Keys.KEY_SECRET_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.SecretRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.SecretRecord>>asList(io.cattle.platform.core.model.Keys.KEY_SECRET_PRIMARY, io.cattle.platform.core.model.Keys.KEY_SECRET_IDX_SECRET_UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<io.cattle.platform.core.model.tables.records.SecretRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<io.cattle.platform.core.model.tables.records.SecretRecord, ?>>asList(io.cattle.platform.core.model.Keys.FK_SECRET__ACCOUNT_ID, io.cattle.platform.core.model.Keys.FK_SECRET__ENVIRONMENT_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.cattle.platform.core.model.tables.SecretTable as(java.lang.String alias) {
		return new io.cattle.platform.core.model.tables.SecretTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.cattle.platform.core.model.tables.SecretTable rename(java.lang.String name) {
		return new io.cattle.platform.core.model.tables.SecretTable(name, null);
	}
}
