/*
 * This file is generated by jOOQ.
*/
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.records.ServiceExposeMapRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceExposeMapTable extends TableImpl<ServiceExposeMapRecord> {

    private static final long serialVersionUID = -1399733001;

    /**
     * The reference instance of <code>cattle.service_expose_map</code>
     */
    public static final ServiceExposeMapTable SERVICE_EXPOSE_MAP = new ServiceExposeMapTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServiceExposeMapRecord> getRecordType() {
        return ServiceExposeMapRecord.class;
    }

    /**
     * The column <code>cattle.service_expose_map.id</code>.
     */
    public final TableField<ServiceExposeMapRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cattle.service_expose_map.name</code>.
     */
    public final TableField<ServiceExposeMapRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>cattle.service_expose_map.kind</code>.
     */
    public final TableField<ServiceExposeMapRecord, String> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>cattle.service_expose_map.uuid</code>.
     */
    public final TableField<ServiceExposeMapRecord, String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

    /**
     * The column <code>cattle.service_expose_map.description</code>.
     */
    public final TableField<ServiceExposeMapRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

    /**
     * The column <code>cattle.service_expose_map.state</code>.
     */
    public final TableField<ServiceExposeMapRecord, String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

    /**
     * The column <code>cattle.service_expose_map.created</code>.
     */
    public final TableField<ServiceExposeMapRecord, Date> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new DateConverter());

    /**
     * The column <code>cattle.service_expose_map.removed</code>.
     */
    public final TableField<ServiceExposeMapRecord, Date> REMOVED = createField("removed", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new DateConverter());

    /**
     * The column <code>cattle.service_expose_map.remove_time</code>.
     */
    public final TableField<ServiceExposeMapRecord, Date> REMOVE_TIME = createField("remove_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new DateConverter());

    /**
     * The column <code>cattle.service_expose_map.data</code>.
     */
    public final TableField<ServiceExposeMapRecord, Map<String,Object>> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB, this, "", new DataConverter());

    /**
     * The column <code>cattle.service_expose_map.service_id</code>.
     */
    public final TableField<ServiceExposeMapRecord, Long> SERVICE_ID = createField("service_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>cattle.service_expose_map.instance_id</code>.
     */
    public final TableField<ServiceExposeMapRecord, Long> INSTANCE_ID = createField("instance_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>cattle.service_expose_map.account_id</code>.
     */
    public final TableField<ServiceExposeMapRecord, Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>cattle.service_expose_map.ip_address</code>.
     */
    public final TableField<ServiceExposeMapRecord, String> IP_ADDRESS = createField("ip_address", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>cattle.service_expose_map.dns_prefix</code>.
     */
    public final TableField<ServiceExposeMapRecord, String> DNS_PREFIX = createField("dns_prefix", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>cattle.service_expose_map.host_name</code>.
     */
    public final TableField<ServiceExposeMapRecord, String> HOST_NAME = createField("host_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>cattle.service_expose_map.managed</code>.
     */
    public final TableField<ServiceExposeMapRecord, Boolean> MANAGED = createField("managed", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'1'", org.jooq.impl.SQLDataType.BIT)), this, "");

    /**
     * The column <code>cattle.service_expose_map.upgrade</code>.
     */
    public final TableField<ServiceExposeMapRecord, Boolean> UPGRADE = createField("upgrade", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "");

    /**
     * The column <code>cattle.service_expose_map.upgrade_time</code>.
     */
    public final TableField<ServiceExposeMapRecord, Date> UPGRADE_TIME = createField("upgrade_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new DateConverter());

    /**
     * Create a <code>cattle.service_expose_map</code> table reference
     */
    public ServiceExposeMapTable() {
        this("service_expose_map", null);
    }

    /**
     * Create an aliased <code>cattle.service_expose_map</code> table reference
     */
    public ServiceExposeMapTable(String alias) {
        this(alias, SERVICE_EXPOSE_MAP);
    }

    private ServiceExposeMapTable(String alias, Table<ServiceExposeMapRecord> aliased) {
        this(alias, aliased, null);
    }

    private ServiceExposeMapTable(String alias, Table<ServiceExposeMapRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CattleTable.CATTLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ServiceExposeMapRecord, Long> getIdentity() {
        return Keys.IDENTITY_SERVICE_EXPOSE_MAP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ServiceExposeMapRecord> getPrimaryKey() {
        return Keys.KEY_SERVICE_EXPOSE_MAP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ServiceExposeMapRecord>> getKeys() {
        return Arrays.<UniqueKey<ServiceExposeMapRecord>>asList(Keys.KEY_SERVICE_EXPOSE_MAP_PRIMARY, Keys.KEY_SERVICE_EXPOSE_MAP_IDX_SERVICE_INSTANCE_MAP_UUID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ServiceExposeMapRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ServiceExposeMapRecord, ?>>asList(Keys.FK_SERVICE_INSTANCE_MAP__SERVICE_ID, Keys.FK_SERVICE_INSTANCE_MAP__INSTANCE_ID, Keys.FK_SERVICE_EXPOSE_MAP__ACCOUNT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceExposeMapTable as(String alias) {
        return new ServiceExposeMapTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceExposeMapTable rename(String name) {
        return new ServiceExposeMapTable(name, null);
    }
}
