/*
 * This file is generated by jOOQ.
*/
package io.cattle.platform.core.model.tables;


import io.cattle.platform.core.model.CattleTable;
import io.cattle.platform.core.model.Keys;
import io.cattle.platform.core.model.tables.records.StoragePoolHostMapRecord;
import io.cattle.platform.db.jooq.converter.DataConverter;
import io.cattle.platform.db.jooq.converter.DateConverter;

import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoragePoolHostMapTable extends TableImpl<StoragePoolHostMapRecord> {

    private static final long serialVersionUID = -1683169775;

    /**
     * The reference instance of <code>cattle.storage_pool_host_map</code>
     */
    public static final StoragePoolHostMapTable STORAGE_POOL_HOST_MAP = new StoragePoolHostMapTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoragePoolHostMapRecord> getRecordType() {
        return StoragePoolHostMapRecord.class;
    }

    /**
     * The column <code>cattle.storage_pool_host_map.id</code>.
     */
    public final TableField<StoragePoolHostMapRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cattle.storage_pool_host_map.name</code>.
     */
    public final TableField<StoragePoolHostMapRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>cattle.storage_pool_host_map.kind</code>.
     */
    public final TableField<StoragePoolHostMapRecord, String> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>cattle.storage_pool_host_map.uuid</code>.
     */
    public final TableField<StoragePoolHostMapRecord, String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

    /**
     * The column <code>cattle.storage_pool_host_map.description</code>.
     */
    public final TableField<StoragePoolHostMapRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

    /**
     * The column <code>cattle.storage_pool_host_map.state</code>.
     */
    public final TableField<StoragePoolHostMapRecord, String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

    /**
     * The column <code>cattle.storage_pool_host_map.created</code>.
     */
    public final TableField<StoragePoolHostMapRecord, Date> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new DateConverter());

    /**
     * The column <code>cattle.storage_pool_host_map.removed</code>.
     */
    public final TableField<StoragePoolHostMapRecord, Date> REMOVED = createField("removed", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new DateConverter());

    /**
     * The column <code>cattle.storage_pool_host_map.remove_time</code>.
     */
    public final TableField<StoragePoolHostMapRecord, Date> REMOVE_TIME = createField("remove_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new DateConverter());

    /**
     * The column <code>cattle.storage_pool_host_map.data</code>.
     */
    public final TableField<StoragePoolHostMapRecord, Map<String,Object>> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB, this, "", new DataConverter());

    /**
     * The column <code>cattle.storage_pool_host_map.storage_pool_id</code>.
     */
    public final TableField<StoragePoolHostMapRecord, Long> STORAGE_POOL_ID = createField("storage_pool_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>cattle.storage_pool_host_map.host_id</code>.
     */
    public final TableField<StoragePoolHostMapRecord, Long> HOST_ID = createField("host_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>cattle.storage_pool_host_map</code> table reference
     */
    public StoragePoolHostMapTable() {
        this("storage_pool_host_map", null);
    }

    /**
     * Create an aliased <code>cattle.storage_pool_host_map</code> table reference
     */
    public StoragePoolHostMapTable(String alias) {
        this(alias, STORAGE_POOL_HOST_MAP);
    }

    private StoragePoolHostMapTable(String alias, Table<StoragePoolHostMapRecord> aliased) {
        this(alias, aliased, null);
    }

    private StoragePoolHostMapTable(String alias, Table<StoragePoolHostMapRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CattleTable.CATTLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StoragePoolHostMapRecord, Long> getIdentity() {
        return Keys.IDENTITY_STORAGE_POOL_HOST_MAP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StoragePoolHostMapRecord> getPrimaryKey() {
        return Keys.KEY_STORAGE_POOL_HOST_MAP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StoragePoolHostMapRecord>> getKeys() {
        return Arrays.<UniqueKey<StoragePoolHostMapRecord>>asList(Keys.KEY_STORAGE_POOL_HOST_MAP_PRIMARY, Keys.KEY_STORAGE_POOL_HOST_MAP_IDX_STORAGE_POOL_HOST_MAP_UUID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<StoragePoolHostMapRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<StoragePoolHostMapRecord, ?>>asList(Keys.FK_STORAGE_POOL_HOST_MAP__STORAGE_POOL_ID, Keys.FK_STORAGE_POOL_HOST_MAP__HOST_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoragePoolHostMapTable as(String alias) {
        return new StoragePoolHostMapTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StoragePoolHostMapTable rename(String name) {
        return new StoragePoolHostMapTable(name, null);
    }
}
