/*
 * This file is generated by jOOQ.
*/
package io.cattle.platform.core.model;


import java.io.Serializable;
import java.util.Date;
import java.util.Map;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "audit_log", schema = "cattle")
public interface AuditLog extends Serializable {

    /**
     * Setter for <code>cattle.audit_log.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.audit_log.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 19)
    public Long getId();

    /**
     * Setter for <code>cattle.audit_log.account_id</code>.
     */
    public void setAccountId(Long value);

    /**
     * Getter for <code>cattle.audit_log.account_id</code>.
     */
    @Column(name = "account_id", precision = 19)
    public Long getAccountId();

    /**
     * Setter for <code>cattle.audit_log.authenticated_as_account_id</code>.
     */
    public void setAuthenticatedAsAccountId(Long value);

    /**
     * Getter for <code>cattle.audit_log.authenticated_as_account_id</code>.
     */
    @Column(name = "authenticated_as_account_id", precision = 19)
    public Long getAuthenticatedAsAccountId();

    /**
     * Setter for <code>cattle.audit_log.kind</code>.
     */
    public void setKind(String value);

    /**
     * Getter for <code>cattle.audit_log.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    public String getKind();

    /**
     * Setter for <code>cattle.audit_log.auth_type</code>.
     */
    public void setAuthType(String value);

    /**
     * Getter for <code>cattle.audit_log.auth_type</code>.
     */
    @Column(name = "auth_type", length = 255)
    public String getAuthType();

    /**
     * Setter for <code>cattle.audit_log.event_type</code>.
     */
    public void setEventType(String value);

    /**
     * Getter for <code>cattle.audit_log.event_type</code>.
     */
    @Column(name = "event_type", nullable = false, length = 255)
    public String getEventType();

    /**
     * Setter for <code>cattle.audit_log.resource_type</code>.
     */
    public void setResourceType(String value);

    /**
     * Getter for <code>cattle.audit_log.resource_type</code>.
     */
    @Column(name = "resource_type", nullable = false, length = 255)
    public String getResourceType();

    /**
     * Setter for <code>cattle.audit_log.resource_id</code>.
     */
    public void setResourceId(Long value);

    /**
     * Getter for <code>cattle.audit_log.resource_id</code>.
     */
    @Column(name = "resource_id", precision = 19)
    public Long getResourceId();

    /**
     * Setter for <code>cattle.audit_log.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>cattle.audit_log.description</code>.
     */
    @Column(name = "description", length = 1024)
    public String getDescription();

    /**
     * Setter for <code>cattle.audit_log.created</code>.
     */
    public void setCreated(Date value);

    /**
     * Getter for <code>cattle.audit_log.created</code>.
     */
    @Column(name = "created")
    public Date getCreated();

    /**
     * Setter for <code>cattle.audit_log.data</code>.
     */
    public void setData(Map<String,Object> value);

    /**
     * Getter for <code>cattle.audit_log.data</code>.
     */
    @Column(name = "data", length = 16777215)
    public Map<String,Object> getData();

    /**
     * Setter for <code>cattle.audit_log.authenticated_as_identity_id</code>.
     */
    public void setAuthenticatedAsIdentityId(String value);

    /**
     * Getter for <code>cattle.audit_log.authenticated_as_identity_id</code>.
     */
    @Column(name = "authenticated_as_identity_id", length = 255)
    public String getAuthenticatedAsIdentityId();

    /**
     * Setter for <code>cattle.audit_log.runtime</code>.
     */
    public void setRuntime(Long value);

    /**
     * Getter for <code>cattle.audit_log.runtime</code>.
     */
    @Column(name = "runtime", precision = 19)
    public Long getRuntime();

    /**
     * Setter for <code>cattle.audit_log.client_ip</code>.
     */
    public void setClientIp(String value);

    /**
     * Getter for <code>cattle.audit_log.client_ip</code>.
     */
    @Column(name = "client_ip", length = 255)
    public String getClientIp();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface AuditLog
     */
    public void from(io.cattle.platform.core.model.AuditLog from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface AuditLog
     */
    public <E extends io.cattle.platform.core.model.AuditLog> E into(E into);
}
