/**
 * This class is generated by jOOQ
 */
package io.cattle.platform.core.model;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "auth_token", schema = "cattle")
public interface AuthToken extends java.io.Serializable {

	/**
	 * Setter for <code>cattle.auth_token.id</code>.
	 */
	public void setId(java.lang.Long value);

	/**
	 * Getter for <code>cattle.auth_token.id</code>.
	 */
	@javax.persistence.Id
	@javax.persistence.Column(name = "id", unique = true, nullable = false, precision = 19)
	public java.lang.Long getId();

	/**
	 * Setter for <code>cattle.auth_token.account_id</code>.
	 */
	public void setAccountId(java.lang.Long value);

	/**
	 * Getter for <code>cattle.auth_token.account_id</code>.
	 */
	@javax.persistence.Column(name = "account_id", nullable = false, precision = 19)
	public java.lang.Long getAccountId();

	/**
	 * Setter for <code>cattle.auth_token.created</code>.
	 */
	public void setCreated(java.util.Date value);

	/**
	 * Getter for <code>cattle.auth_token.created</code>.
	 */
	@javax.persistence.Column(name = "created", nullable = false)
	public java.util.Date getCreated();

	/**
	 * Setter for <code>cattle.auth_token.expires</code>.
	 */
	public void setExpires(java.util.Date value);

	/**
	 * Getter for <code>cattle.auth_token.expires</code>.
	 */
	@javax.persistence.Column(name = "expires", nullable = false)
	public java.util.Date getExpires();

	/**
	 * Setter for <code>cattle.auth_token.key</code>.
	 */
	public void setKey(java.lang.String value);

	/**
	 * Getter for <code>cattle.auth_token.key</code>.
	 */
	@javax.persistence.Column(name = "key", unique = true, nullable = false, length = 40)
	public java.lang.String getKey();

	/**
	 * Setter for <code>cattle.auth_token.value</code>.
	 */
	public void setValue(java.lang.String value);

	/**
	 * Getter for <code>cattle.auth_token.value</code>.
	 */
	@javax.persistence.Column(name = "value", nullable = false, length = 16777215)
	public java.lang.String getValue();

	/**
	 * Setter for <code>cattle.auth_token.version</code>.
	 */
	public void setVersion(java.lang.String value);

	/**
	 * Getter for <code>cattle.auth_token.version</code>.
	 */
	@javax.persistence.Column(name = "version", nullable = false, length = 255)
	public java.lang.String getVersion();

	/**
	 * Setter for <code>cattle.auth_token.provider</code>.
	 */
	public void setProvider(java.lang.String value);

	/**
	 * Getter for <code>cattle.auth_token.provider</code>.
	 */
	@javax.persistence.Column(name = "provider", nullable = false, length = 255)
	public java.lang.String getProvider();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface AuthToken
	 */
	public void from(io.cattle.platform.core.model.AuthToken from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface AuthToken
	 */
	public <E extends io.cattle.platform.core.model.AuthToken> E into(E into);
}
