/*
 * This file is generated by jOOQ.
*/
package io.cattle.platform.core.model;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "dynamic_schema_role", schema = "cattle")
public interface DynamicSchemaRole extends Serializable {

    /**
     * Setter for <code>cattle.dynamic_schema_role.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>cattle.dynamic_schema_role.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 19)
    public Long getId();

    /**
     * Setter for <code>cattle.dynamic_schema_role.dynamic_schema_id</code>.
     */
    public void setDynamicSchemaId(Long value);

    /**
     * Getter for <code>cattle.dynamic_schema_role.dynamic_schema_id</code>.
     */
    @Column(name = "dynamic_schema_id", precision = 19)
    public Long getDynamicSchemaId();

    /**
     * Setter for <code>cattle.dynamic_schema_role.role</code>.
     */
    public void setRole(String value);

    /**
     * Getter for <code>cattle.dynamic_schema_role.role</code>.
     */
    @Column(name = "role", nullable = false, length = 255)
    public String getRole();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface DynamicSchemaRole
     */
    public void from(io.cattle.platform.core.model.DynamicSchemaRole from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface DynamicSchemaRole
     */
    public <E extends io.cattle.platform.core.model.DynamicSchemaRole> E into(E into);
}
