#!/bin/bash
### BEGIN INIT INFO
# Provides:		cluster
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	swarm cluster
# Description:		swarm cluster
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
SWARM_ARG_FILE=/etc/cluster/swarm_args.conf
SWARM_ARGS=$(cat ${SWARM_ARG_FILE})
PIDFILE=/var/run/swarm.pid

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting swarm server" || true
	if start-stop-daemon --start -b --pidfile $PIDFILE --make-pidfile --exec /usr/bin/swarm -- $SWARM_ARGS
	then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping swarm server" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --exec /usr/bin/swarm
	then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
esac
:
exit 0

