#!/bin/bash
set -e

cd $(dirname $0)/..

if [ -z "$API_VERSION" ] || [ "$API_VERSION" = "v3" ]; then
    cd tests/integration
else
    cd tests/integration-${API_VERSION}
fi

export CATTLE_URL=http://localhost:8080/v3/schemas

if [ -e .tox ] && [ ! -e .tox/py27/include/python2.7 ]; then
    rm -rf .tox
fi

tox "$@"
