/**
 * This class is generated by jOOQ
 */
package io.github.ibuildthecloud.dstack.core.model;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "agent", schema = "dstack")
public interface Agent extends java.io.Serializable {

	/**
	 * Setter for <code>dstack.agent.id</code>. 
	 */
	public void setId(java.lang.Long value);

	/**
	 * Getter for <code>dstack.agent.id</code>. 
	 */
	@javax.persistence.Id
	@javax.persistence.Column(name = "id", unique = true, nullable = false, precision = 19)
	public java.lang.Long getId();

	/**
	 * Setter for <code>dstack.agent.name</code>. 
	 */
	public void setName(java.lang.String value);

	/**
	 * Getter for <code>dstack.agent.name</code>. 
	 */
	@javax.persistence.Column(name = "name", length = 255)
	public java.lang.String getName();

	/**
	 * Setter for <code>dstack.agent.description</code>. 
	 */
	public void setDescription(java.lang.String value);

	/**
	 * Getter for <code>dstack.agent.description</code>. 
	 */
	@javax.persistence.Column(name = "description", length = 1024)
	public java.lang.String getDescription();

	/**
	 * Setter for <code>dstack.agent.kind</code>. 
	 */
	public void setKind(java.lang.String value);

	/**
	 * Getter for <code>dstack.agent.kind</code>. 
	 */
	@javax.persistence.Column(name = "kind", nullable = false, length = 255)
	public java.lang.String getKind();

	/**
	 * Setter for <code>dstack.agent.data</code>. 
	 */
	public void setData(java.util.Map<String,Object> value);

	/**
	 * Getter for <code>dstack.agent.data</code>. 
	 */
	@javax.persistence.Column(name = "data", length = 16777215)
	public java.util.Map<String,Object> getData();

	/**
	 * Setter for <code>dstack.agent.agent_group_id</code>. 
	 */
	public void setAgentGroupId(java.lang.Long value);

	/**
	 * Getter for <code>dstack.agent.agent_group_id</code>. 
	 */
	@javax.persistence.Column(name = "agent_group_id", precision = 19)
	public java.lang.Long getAgentGroupId();

	/**
	 * Setter for <code>dstack.agent.state</code>. 
	 */
	public void setState(java.lang.String value);

	/**
	 * Getter for <code>dstack.agent.state</code>. 
	 */
	@javax.persistence.Column(name = "state", nullable = false, length = 255)
	public java.lang.String getState();

	/**
	 * Setter for <code>dstack.agent.uri</code>. 
	 */
	public void setUri(java.lang.String value);

	/**
	 * Getter for <code>dstack.agent.uri</code>. 
	 */
	@javax.persistence.Column(name = "uri", length = 255)
	public java.lang.String getUri();

	/**
	 * Setter for <code>dstack.agent.account_id</code>. 
	 */
	public void setAccountId(java.lang.Long value);

	/**
	 * Getter for <code>dstack.agent.account_id</code>. 
	 */
	@javax.persistence.Column(name = "account_id", precision = 19)
	public java.lang.Long getAccountId();

	/**
	 * Setter for <code>dstack.agent.created</code>. 
	 */
	public void setCreated(java.sql.Timestamp value);

	/**
	 * Getter for <code>dstack.agent.created</code>. 
	 */
	@javax.persistence.Column(name = "created", nullable = false)
	public java.sql.Timestamp getCreated();

	/**
	 * Setter for <code>dstack.agent.uuid</code>. 
	 */
	public void setUuid(java.lang.String value);

	/**
	 * Getter for <code>dstack.agent.uuid</code>. 
	 */
	@javax.persistence.Column(name = "uuid", nullable = false, length = 128)
	public java.lang.String getUuid();

	/**
	 * Setter for <code>dstack.agent.removed</code>. 
	 */
	public void setRemoved(java.sql.Timestamp value);

	/**
	 * Getter for <code>dstack.agent.removed</code>. 
	 */
	@javax.persistence.Column(name = "removed")
	public java.sql.Timestamp getRemoved();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface Agent
	 */
	public void from(io.github.ibuildthecloud.dstack.core.model.Agent from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface Agent
	 */
	public <E extends io.github.ibuildthecloud.dstack.core.model.Agent> E into(E into);
}
