#!/bin/bash

eval $(cat /proc/1/environ 2>/dev/null | xargs -0 -I{} echo export '"{}"' | grep CATTLE_)

if [[ -n "$CATTLE_AGENT_INSTANCE_AUTH" && -z "$CATTLE_ACCESS_KEY" && -z "$CATTLE_SECRET_KEY" ]]; then
    CATTLE_ACCESS_KEY=$(echo $CATTLE_AGENT_INSTANCE_AUTH | sed 's/Basic //' | base64 -d | cut -f1 -d:)
    CATTLE_SECRET_KEY=$(echo $CATTLE_AGENT_INSTANCE_AUTH | sed 's/Basic //' | base64 -d | cut -f2 -d:)
fi

touch /var/run/haproxy-monitor.conf
chmod 600 /var/run/haproxy-monitor.conf

cat > /var/run/haproxy-monitor.conf << EOF
cattle-url = $CATTLE_CONFIG_URL
cattle-access-key = $CATTLE_ACCESS_KEY
cattle-secret-key = $CATTLE_SECRET_KEY
EOF

export HOST_API_CONFIG_FILE=/var/run/haproxy-monitor.conf
