FROM ibuildthecloud/ubuntu-core-base:13.10
RUN apt-get update && apt-get install -y --no-install-recommends openjdk-7-jre-headless
RUN apt-get update && apt-get install -y curl
ADD artifacts /var/lib/dstack
RUN DSTACK_SSH_KEYGEN_ON_STARTUP=false /var/lib/dstack/dstack.sh --exit
CMD ["/var/lib/dstack/dstack.sh"]
EXPOSE 8080
